plugins {
    //alias libs.plugins.org.jetbrains.kotlin.jvm
    alias libs.plugins.nl.littlerobots.version.catalog.update
    id 'idea'
    id 'java'
}

dependencies {
}

allprojects {
    apply plugin: 'idea'
    group="ditz"

    repositories {
        mavenCentral()
    }

    plugins.withType(JavaPlugin).tap {
        configureEach {

            idea {
                module {
                    outputDir = file('build/idea/main')
                    testOutputDir = file('build/idea/test')
                }
            }

            dependencies {
                testImplementation libs.org.junit.jupiter.engine
            }
        }
    }
}
